# Generated by Django 3.0.7 on 2021-03-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=64)),
                ('codigo_ciiu', models.CharField(max_length=5)),
                ('camara', models.CharField(max_length=6)),
                ('direccion', models.CharField(max_length=32)),
                ('telefono', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=32)),
                ('pagina_web', models.CharField(max_length=25)),
                ('tipo_empresa', models.CharField(max_length=7)),
                ('tipo_gda', models.CharField(max_length=12)),
                ('fecha_registro_emp', models.DateField()),
                ('fecha_creaciondga', models.DateField()),
                ('decreto_1076', models.CharField(max_length=2)),
                ('sector_productivo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcionario', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('nombre_mpio', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('codigo_mpio', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seg', models.DateField()),
                ('resultado', models.CharField(max_length=64)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.Empresa')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.Funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='idrepresentante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.Representante'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_mpio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.Municipio'),
        ),
        migrations.CreateModel(
            name='Dga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_responsable', models.CharField(max_length=50)),
                ('nivel_estudio', models.CharField(max_length=22)),
                ('titulo', models.CharField(max_length=25)),
                ('cargo', models.CharField(max_length=25)),
                ('email_dga', models.EmailField(max_length=254)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.Empresa')),
            ],
        ),
    ]
