# Generated by Django 3.0.7 on 2021-03-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='fecha_creaciondga',
            new_name='fecha_creacion_dga',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre_mpio',
            new_name='municipio',
        ),
    ]
