# Generated by Django 3.0.7 on 2021-03-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0002_auto_20210326_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
