# Generated by Django 3.0.7 on 2021-03-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0003_auto_20210326_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
