# Generated by Django 3.0.7 on 2021-03-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0004_auto_20210326_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='idrepresentante',
            new_name='cedula_representante',
        ),
        migrations.RenameField(
            model_name='representante',
            old_name='id',
            new_name='cedula',
        ),
    ]
