# Generated by Django 3.0.7 on 2021-03-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0005_auto_20210326_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dga',
            old_name='id',
            new_name='id_dga',
        ),
        migrations.RemoveField(
            model_name='dga',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Responsable_DGA',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.CASCADE, to='gestiondga.DGA'),
            preserve_default=False,
        ),
    ]
