# Generated by Django 3.0.7 on 2021-03-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0008_auto_20210327_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Responsable_DGA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.DGA'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decreto_1076',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('GRANDE', 'GRANDE'), ('MEDIANA', 'PEQUEÑA'), ('PEQUEÑA', 'PEQUEÑA'), ('MICRO', 'MICRO')], default='GRANDE', max_length=7, verbose_name='Su Empresa es:'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_gda',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO'), ('APOYO GREMIO', 'APOYO GREMIO')], default='INTERNO', max_length=12, verbose_name='Tipo Departamento Gestion Ambiental'),
        ),
    ]
