# Generated by Django 3.0.7 on 2021-03-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0012_auto_20210327_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Responsable_DGA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.DGA'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombre_rep',
            field=models.CharField(max_length=50, verbose_name='Nombre Representante Legal'),
        ),
    ]
