# Generated by Django 3.0.7 on 2021-03-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondga', '0013_auto_20210327_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_creacion_dga',
        ),
        migrations.AddField(
            model_name='dga',
            name='fecha_creacion_dga',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Responsable_DGA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondga.DGA'),
        ),
    ]
